### ISSUE TITLE
links on crate homepage are broken

### ISSUE THREAD

**Issue by hoodie** [d-unseductable/ruru#14]
Hi there,
I was just looking at https://crates.io/crates/ruby-sys and found that the homepage and documentation links are not working.

**Comment by steveklabnik** [comment]
ah, right; I wrote these by hand, and apparently didn't do a good job of checking.

@d-unseductable this begs the question, maybe we should split the other crate out of this repo? I can have that one, you can have this one, hehe

**Comment by d-unseductable** [comment]
@steveklabnik yeah I've thought about splitting earlier today 😄 It's a bit annoying that you need to commit and push to the same repo, but then publish as separate crates. Anyway let's merge #15 first as it affects for both `ruru` and `ruby-sys`

**Comment by steveklabnik** [comment]
:+1:

**Comment by d-unseductable** [comment]
@steveklabnik the PR was merged, so let's do it 😄

**Comment by steveklabnik** [comment]
https://github.com/steveklabnik/ruby-sys <- what do you think? :) I was able to extract the history out with

```
 $ git filter-branch --prune-empty --subdirectory-filter  ruby-sys master
```

If this looks good, I will submit a PR to have ruru depend on this, and add you as a collaborator :smile:

**Comment by malept** [comment]
@steveklabnik seems to be missing @d-unseductable's latest PR.

**Comment by steveklabnik** [comment]
@malept nice call! my local checkout was out of date. look at it now

**Comment by d-unseductable** [comment]
:+1:

**Comment by steveklabnik** [comment]
Fixed by https://github.com/steveklabnik/ruby-sys/commit/c2fc860e8964601622062add28c890dd4001f68f , thanks!

I am going to do a few other things and push up a new release, which will fix the links on crates.io.

**Comment by steveklabnik** [comment]
Done! https://crates.io/crates/ruby-sys
