### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by Ch4s3** [d-unseductable/ruru#23]
Is the "How do I use it?" section of the readme up to date? I'm interested in checking out the project, but wanted to see if the readme is up to date before digging in.

**Comment by malept** [comment]
The examples in the README should be up-to-date. I'm using [the `blank?` example](https://github.com/malept/rusty_blank) to prototype [Rust+Ruby extension packaging and distribution](https://github.com/malept/thermite).

**Comment by Ch4s3** [comment]
Awesome, thanks!
