### ISSUE TITLE
ruru vs. helix 

### ISSUE THREAD

**Issue by ordian** [d-unseductable/ruru#26]
How does ruru compare to [Helix](https://github.com/rustbridge/helix) by Yehuda Katz?

**Comment by d-unseductable** [comment]
Hi @ordian!

As nobody replied to the issue since June, it seems that there are not so many people who compared both crates.

I will close it, but please feel free to re-open if you have something share.

**Comment by NullVoxPopuli** [comment]
I was super interested in helix, as the APIs look a tad nicer than ruru. but I'll hopefully be using ruru in my case_transform project, cause helix is no where near "production" ready
