### ISSUE TITLE
Add AppVeyor CI (Windows) support

### ISSUE THREAD

**Issue by malept** [d-unseductable/ruru#27]
As of `ruby-sys` 0.2.3, ruru-based extensions can be built on Windows. It would be nice to add CI support for Windows builds.

A starting point can be found at my `rusty_blank` project: https://github.com/malept/rusty_blank/blob/master/.appveyor.yml

Some notes about my config file:
* You probably want to test against stable, beta, and nightly (I only needed stable there).
* I intentionally omitted MSVC builds from my AppVeyor config because the popular RubyInstaller for Windows is built with the MinGW toolchain.
* Ignore the artifact/deploy sections - that is for my [project to distribute Rust+Ruby extensions](https://github.com/malept/thermite).

**Comment by d-unseductable** [comment]
Hi @malept!

Thank you, I'll take a look at it tomorrow

**Comment by d-unseductable** [comment]
Thanks, AppVeyor support enabled!
