### ISSUE TITLE
0.7.6 fails to build on Windows

### ISSUE THREAD

**Issue by malept** [d-unseductable/ruru#28]
Ruru 0.7.6 [doesn't currently compile on Windows](https://ci.appveyor.com/project/malept/rusty-blank/build/1.0.49/job/bdq2g0cvwfip7nk4#L100), I can follow up with a patch later today (Pacific time).

**Comment by d-unseductable** [comment]
Oh thank you!

I'm gonna release new version in a few mins, so I'll include a patch there.

**Comment by d-unseductable** [comment]
Fixed with @aff9f0c2645dc5195c32a9d56c06a748769b417f

Please update crate version to `0.7.7`
