### ISSUE TITLE
Steal helix' macro API

### ISSUE THREAD

**Issue by killercup** [d-unseductable/ruru#36]
Would it make sense to adapt [helix' macro API](https://github.com/rustbridge/helix/blob/2c057f04bf130f2a25ef8ac006290c0f81abe350/src/macros.rs)?

I've just come across ruru and saw that it uses macros to define types, but they are not _quite_ as concise as the ones in helix (and you need to specify an unmangled function which helix for some reason doesn't). The class definition DSL seems okay but defining classes in a macro that makes the code look like Ruby might go a long way in convincing Ruby programmers to try this Rust thing :)

**Comment by d-unseductable** [comment]
Hey @killercup!

I totally agree that it's good to have a nice API for classes! I believe every rubyist likes good-looking APIs :)

It has not been a priority for some time, but since Ruru is moving towards 1.0, it is time to start working on class definitions. I created #58 for discussions.
