### ISSUE TITLE
"This Week in Ruru" needs a summary at the top of each entry

### ISSUE THREAD

**Issue by malept** [d-unseductable/ruru#37]
_Since the "This Week in Ruru" website doesn't have a public repository, I'm filing it here._

Each blog entry to "This Week in Ruru" should have a description of what Ruru is at the top so people who are directly linked to the post from, for example, Reddit, know the context of the changes/news described.

**Comment by d-unseductable** [comment]
👍 Thanks for pointing this out! I've added a header with description to blog posts.
