### ISSUE TITLE
What's the best way to reuse code or define helper methods inside `methods!`macro?

### ISSUE THREAD

**Issue by simon0191** [d-unseductable/ruru#42]
If I define `some_helper_method` inside `methods!` macro and try to call it inside other method defined inside `methods!` macro I get these errors:
``` 
     some_helper_method();
   | ^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
src/lib.rs:7:1: 109:3 note: in this expansion of methods! (defined in <ruru macros>)
   |
   = note: the following parameter types were expected: i32, *const ruru::AnyObject, SomeClass
```
So... What's the best way to declare some helper methods to reuse code?

**Comment by d-unseductable** [comment]
`methods!` macro should be used to define only those methods which are exposed to Ruby (those ones which are used in `def` and `def_self`). You should move "helper functions" outside the `methods!` macro.

Long story short, Ruby methods and Rust functions are different and those functions which are declared inside `methods!` macro are transformed during compile-time to be compatible with MRI.

For example, printing some message to stdout from several Ruby methods:

```rust
fn print_message(message: &str) {
    println!("{}", message);
}

class!(Printer);

methods!(
    Printer,
    itself,

    fn print_hello() -> NilClass {
        print_message("Hello!");

        NilClass::new()
    }

    fn print_good_bye() -> NilClass {
        print_message("Good bye!");

        NilClass::new()
    }
}

fn main() {
    Class::new("Printer", None).define(|itself| {
        itself.def("print_hello", print_hello);
        itself.def("print_good_bye", print_good_bye);
    });
}
```

**Comment by Zapotek** [comment]
It may also be a good idea to treat Ruru methods as simple translators:

1. Use Ruru defined methods to unwrap and convert their arguments to Rust objects.
2. Pass arguments to outside methods that do all the work.
3. Convert Rust return value to Ruby.

Will help with reuse and allow you to adapt to future API changes.
