### ISSUE TITLE
This Week in Ruru: broken link

### ISSUE THREAD

**Issue by malept** [d-unseductable/ruru#44]
[From Reddit](https://www.reddit.com/r/rust/comments/596w41/these_weeks_in_ruru_3/d96mc1e/):

> The link for "the last issue" is broken:
>
> http://localhost:4000/2016/10/04/this-weeks-in-ruru-2/
>
> instead of
>
> http://this-week-in-ruru.org/2016/10/04/this-weeks-in-ruru-2/

Just to be clear, this refers to http://this-week-in-ruru.org/2016/10/24/this-weeks-in-ruru-3/, in:

> As you may know, it was mentioned that this website was powered by Trusted server **in the last issue**.

_(bolded the broken link)_

**Comment by d-unseductable** [comment]
@malept thank you! Fixed
