### ISSUE TITLE
Support for Float and Bignum

### ISSUE THREAD

**Issue by Zapotek** [d-unseductable/ruru#45]
Could you please add support for `Float` and `Bignum` classes when you get a chance?

Cheers

**Comment by elifoster** [comment]
Bignum is removed in ruby 2.4. What version does ruru target @d-unseductable?

**Comment by d-unseductable** [comment]
Hi @zapotek @elifoster 

@turboladen has recently started implementing `Float` in ruby-sys steveklabnik/ruby-sys#11

As for `Bignum` and ruby 2.4. I would like to support the edge ruby version and not support deprecated stuff or something that is going to be removed. It may add overhead having backwards compatibility.

I believe, those developers who are ready to use cutting edge technologies like Rust to increase the performance of their applications, are ok with updating MRI once per year :)

**Comment by Zapotek** [comment]
Once per year is fine, it's the time of the transition that's the issue.
There are usually Gems that take some time to get updated to support the latest Ruby versions and thus keep us outdated for a few months.

Especially in the case of Ruby 2.4 with its internal changes.

**Comment by turboladen** [comment]
So here's the PR for `Float`: #46

**Comment by Zapotek** [comment]
Good enough for now, my need for Bignum went away with the introduction of wrapped data.

Thanks guys, much appreciated.
